### ISSUE TITLE
Update to QGIS 3

### ISSUE THREAD

**Issue by benhur07b** [mpetroff/qgsazimuth#15]
Hi @mpetroff!

First of all, thanks for this plugin. 

I would just like to ask if there are any plans to update this plugin for QGIS 3. I tried downloading the zip and installing it in the nightly build of QGIS 3 but it said that the plugin is broken.

Also, I'm willing to help in updating the plugin to QGIS 3 if there is a plan to do so. Just tell me what needs to be done.

Again, thanks!

**Comment by mpetroff** [comment]
There are [significant changes](https://qgis.org/api/api_break.html) to the plugins API between QGIS 2.x and 3, not to mention the switch from Python 2 to 3, so the current version will not work. I have no intention of trying to support both versions at the same time, since doing so would be rather messy, so I don't want to port the plugin to QGIS 3 until close to its release. It seems like that is soon, but I unfortunately can't seem to find any recent references to an actual release date.

**Comment by gojosh** [comment]
Hi @mpetroff! Just checking in to see if you still have plans to update the plugin? Looks fantastic.

Thanks!

**Comment by mpetroff** [comment]
Once Linux Mint 19 is released and I can easily upgrade to QGIS 3.0 on my development machine, I'll port the plugin. This will probably be early July.

**Comment by mr-han-solo** [comment]
Greetings Sir,

I was wondering if there was an update on how the port to 3.0 was going?

Thanks.

**Comment by mpetroff** [comment]
I have QGIS 3.0 installed now. However, I have not yet gotten around to working on porting the plugin.

**Comment by mr-han-solo** [comment]
Thank you. Just installed it and when I went to open the plugin, I had the following Python error:

WARNING    Traceback (most recent call last):
              File "AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgsAzimuth\qgsAzimuth.py", line 192, in run
              self.loadConf() # get config data
              File "AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgsAzimuth\qgsAzimuth.py", line 1019, in loadConf
              self.pluginGui.move(position)
             TypeError: arguments did not match any overloaded call:
              move(self, QPoint): argument 1 has unexpected type 'QVariant'
              move(self, int, int): argument 1 has unexpected type 'QVariant'
